sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache: npm
branches:
  except:
    - master
  only:
    - working
install:
  - npm install
before_script:
  - npm install -g hexo-cli
script:
  - hexo generate
after_script:
  - cd public
  - echo " www.zhenian.com " > README.md
  - git init
  - git config user.name "zhenian"
  - git config user.email "zhenian@qq.com"
  - git add .
  - git commit -m "re-init from travis"
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/zhenian/zhenian.github.io.git
